# Matrix Inverse and Systems of Equations Activity



In [1]:
import numpy as np

## Problem 1: Finding the Inverse of a Matrix

In [2]:
# Define a 3x3 matrix
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Check if the matrix is invertible
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    print("Inverse of A:")
    print(A_inv)
else:
    print("Matrix A is not invertible.")

# Verify the inverse by multiplying A and A_inv
if det_A != 0:
    identity = np.dot(A, A_inv)
    print("\nA * A_inv (should be close to the identity matrix):")
    print(np.round(identity, decimals=10))  # Rounding to avoid floating-point errors

Determinant of A: 0.9999999999999964
Inverse of A:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

A * A_inv (should be close to the identity matrix):
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


## Problem 2: Solving a System of Linear Equations

In [3]:
# Define the coefficient matrix
A = np.array([[2, 1, -1],
              [1, 3, 2],
              [3, -2, 1]])

# Define the constant vector
b = np.array([8, 10, 3])

# Check if A is invertible
if np.linalg.det(A) != 0:
    # Solve for x using matrix inverse
    x = np.linalg.inv(A).dot(b)
    print("Solution [x, y, z]:")
    print(x)

    # Verify the solution
    print("\nVerification (A * x should equal b):")
    print(np.dot(A, x))
else:
    print("Matrix A is not invertible, no unique solution.")

Solution [x, y, z]:
[ 2.7  2.5 -0.1]

Verification (A * x should equal b):
[ 8. 10.  3.]


## Problem 3: Solving a Real-world Problem

In [4]:
# Define the coefficient matrix for the alloy problem
A = np.array([[0.3, 0.4, 0.3],
              [0.2, 0.4, 0.4],
              [1, 1, 1]])

# Define the constant vector
b = np.array([66, 72, 200])

# Solve for the amounts of each metal
if np.linalg.det(A) != 0:
    x = np.linalg.inv(A).dot(b)
    print("Amounts of each metal [Copper, Zinc, Tin] in kg:")
    print(np.round(x, decimals=2))
else:
    print("The system has no unique solution.")

# Verify the solution
print("\nVerification (percentages should match the given constraints):")
print(f"Copper: {x[0]/2:.1f}%, Zinc: {x[1]/2:.1f}%, Tin: {x[2]/2:.1f}%")
print(f"Total weight: {np.sum(x):.2f} kg")

Amounts of each metal [Copper, Zinc, Tin] in kg:
[ 40.  60. 100.]

Verification (percentages should match the given constraints):
Copper: 20.0%, Zinc: 30.0%, Tin: 50.0%
Total weight: 200.00 kg


## Problem 4: Inverse of a 4x4 Matrix

In [5]:
# Define a 4x4 matrix
B = np.array([[1, 2, 3, 4],
              [0, 1, 2, 3],
              [0, 0, 1, 2],
              [0, 0, 0, 1]])

# Check if the matrix is invertible
det_B = np.linalg.det(B)
print(f"Determinant of B: {det_B}")

if det_B != 0:
    # Calculate the inverse
    B_inv = np.linalg.inv(B)
    print("\nInverse of B:")
    print(B_inv)

    # Verify the inverse
    identity = np.dot(B, B_inv)
    print("\nB * B_inv (should be close to the identity matrix):")
    print(np.round(identity, decimals=10))  # Rounding to avoid floating-point errors
else:
    print("Matrix B is not invertible.")

Determinant of B: 1.0

Inverse of B:
[[ 1. -2.  1.  0.]
 [ 0.  1. -2.  1.]
 [ 0.  0.  1. -2.]
 [ 0.  0.  0.  1.]]

B * B_inv (should be close to the identity matrix):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Problem 5: Solving a System with a 4x4 Matrix

In [6]:
# Define the coefficient matrix
C = np.array([[1, 1, 1, 1],
              [1, 2, 3, 4],
              [1, 3, 6, 10],
              [1, 4, 10, 20]])

# Define the constant vector
d = np.array([10, 30, 70, 140])

# Check if C is invertible
if np.linalg.det(C) != 0:
    # Solve for x using matrix inverse
    x = np.linalg.inv(C).dot(d)
    print("Solution [a, b, c, d]:")
    print(x)

    # Verify the solution
    print("\nVerification (C * x should equal d):")
    print(np.dot(C, x))
else:
    print("Matrix C is not invertible, no unique solution.")

Solution [a, b, c, d]:
[-1.70530257e-13  1.00000000e+01 -1.00000000e+01  1.00000000e+01]

Verification (C * x should equal d):
[ 10.  30.  70. 140.]


## Bonus Challenge: Function to Check Invertibility and Return Inverse

In [7]:
def check_and_invert(matrix):
    """Check if a matrix is invertible and return its inverse if it is."""
    try:
        # Check if the matrix is square
        if matrix.shape[0] != matrix.shape[1]:
            raise ValueError("Matrix must be square.")

        # Check if the matrix is invertible
        det = np.linalg.det(matrix)
        if np.isclose(det, 0):
            print("Matrix is not invertible.")
            return None

        # Calculate and return the inverse
        inverse = np.linalg.inv(matrix)
        return inverse

    except np.linalg.LinAlgError:
        print("Matrix is not invertible.")
        return None

# Test the function with different matrices
matrices = [
    np.array([[1, 2], [3, 4]]),  # Invertible 2x2
    np.array([[1, 2], [2, 4]]),  # Non-invertible 2x2
    np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),  # Non-invertible 3x3
    np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])   # Invertible 3x3
]

for i, matrix in enumerate(matrices, 1):
    print(f"\nMatrix {i}:")
    print(matrix)
    inverse = check_and_invert(matrix)
    if inverse is not None:
        print("Inverse:")
        print(inverse)
        print("Verification (should be close to identity):")
        print(np.round(np.dot(matrix, inverse), decimals=10))


Matrix 1:
[[1 2]
 [3 4]]
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Verification (should be close to identity):
[[1. 0.]
 [0. 1.]]

Matrix 2:
[[1 2]
 [2 4]]
Matrix is not invertible.

Matrix 3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix is not invertible.

Matrix 4:
[[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
Verification (should be close to identity):
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
